### ISSUE TITLE
Changing the value of isSecure doesn't update UI

### ISSUE THREAD

**Issue by nmn** [benjaminsage/iTextField#3]
I believe this is because all the modifier values aren't being set in the updateView method of the UIViewRepresentable

**Comment by OrkhanAlikhanov** [comment]
Were you able to get round this?

**Comment by OrkhanAlikhanov** [comment]
Your PR #4 fixes this but it that change is not released under a version

**Comment by AlexFine** [comment]
Will review this shortly. Have been very busy lately.

**Comment by AlexFine** [comment]
Just released a new version with that PR included. Sorry for the delay!
